### ISSUE TITLE
clé de langue notification

### ISSUE THREAD

**Issue by Galixte** [maelsoucaze/phpbb#2]
Salut @maelsoucaze,

https://github.com/maelsoucaze/phpbb/blob/master/language/fr/email/topic_notify.txt#L5 

Voir : http://forums.phpbb-fr.com/discussions-phpbb3/sujet202470-120.html#p1606819

**Comment by Galixte** [comment]
Fixed here: https://github.com/maelsoucaze/phpbb/commit/0083d8ce6f5a50e3e41206d9ab87245bd6614587.

**Comment by maelsoucaze** [comment]
Salut @Galixte !

Merci mais comme tu as vu par la suite, j'avais déjà corrigé ça. C'est l'intention qui compte !

J'ai également bien reçu tes autres commentaires, merci de tes contributions, je regarderai et corrigerai ça dès que possible sur les différentes versions de la traduction. :grinning:

**Comment by Galixte** [comment]
Salut,

mon premier message date du 25 juillet : https://github.com/maelsoucaze/phpbb/issues/2#issue-97233196.

Aujourd’hui, j’ai uniquement ajouté le ```@maelsoucaze``` dans le premier message et ainsi qu’une réponse à titre informatif.

Bonne continuation !

**Comment by maelsoucaze** [comment]
Bizarre, je n'avais pas reçu de notification.

En tout cas merci beaucoup ! :+1:
